/**
 * @author: Quintin Mudge
 * Date: 28/02/2017
 * Description: Main GUI interface, User search for content page.
 */
package co.za.wildlife;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Administrator login form. Logs user into Administration form.
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * user input variables.
     */
    String name = null;
    String password = null;

    /**
     * Takes user input and checks it against the database for authenticity.
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * Design and layout, initializes the form. WARNING: Do NOT modify this
     * code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        continueBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Login");
        setLocation(new java.awt.Point(600, 350));

        userNameLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        userNameLbl.setText("User Name :");

        passwordLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        passwordLbl.setText("Password :");

        continueBtn.setText("Continue");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userNameLbl)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(passwordLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event listener for user input submission via continue button.
     */
    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed

        //user input variables declared.
        name = nameTxt.getText() + ",";
        password = new String(passwordTxt.getPassword());

        //Starts admin client that connects to server
        try {
            this.dispose();
            AdminLoginClient();
        } catch (IOException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_continueBtnActionPerformed

    /**
     * Creates new client connection that checks and handle administrator login
     * details.
     */
    private void AdminLoginClient() throws IOException {

        //client connection variables.
        Socket clientSocket = null;
        PrintWriter out = null;
        BufferedReader in = null;

        //New client connection.
        try {
            clientSocket = new Socket("127.0.0.1", 7777
            );
            out = new PrintWriter(clientSocket.getOutputStream(), true);
            in = new BufferedReader(new InputStreamReader(
                    clientSocket.getInputStream()));
        } catch (UnknownHostException e) {
            System.err.println("Don't know about host: 127.0.0.1");
            System.exit(1);
        } catch (IOException e) {

            //Custom dialog box, Tells user that they can not connect to server.
            JOptionPane.showConfirmDialog(null,
                    "Unable to connect to server.\nMake sure that server is"
                    + " running and try again.",
                    "Connection Error",
                    JOptionPane.CANCEL_OPTION,
                    JOptionPane.ERROR_MESSAGE
            );
            System.exit(0);
        }
        BufferedReader line = new BufferedReader(new InputStreamReader(
                System.in));

        String fromServer;
        String fromUser;

        //User input sent as String to server.
        while ((fromServer = in.readLine()) != null) {
            System.out.println("Server: " + fromServer);
            fromUser = name + password;

            //Check that the string contains a number.
            if (fromUser.matches(".*\\d+.*")) {
                System.out.println("Client: " + fromUser);
                out.println(fromUser);
                break;

                //Display dialog error message for incorrect input.   
            } else {
                JOptionPane.showConfirmDialog(null,
                        "Incorrect Password",
                        "Input Error",
                        JOptionPane.CANCEL_OPTION,
                        JOptionPane.ERROR_MESSAGE
                );
                break;
            }
        }
        fromServer = in.readLine();

        //Split the string and stores values inside array.
        String[] myCheck = fromServer.split(",");

        //Checks that values match and then launches administrator GUI form.
        if (name.equals(myCheck[0] + ",") && password.equals(myCheck[1])) {
            new AdminGui().setVisible(true);

            //Error display dialog box for incorrect input.    
        } else {
            JOptionPane.showConfirmDialog(null,
                    "Incorrect Username or Password",
                    "Input Error",
                    JOptionPane.CANCEL_OPTION,
                    JOptionPane.ERROR_MESSAGE
            );
        }

        //Close client connections.
        out.close();
        in.close();
        line.close();
        clientSocket.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueBtn;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables
}
